### PR TITLE
Add a candidate's latest tweets, where available.

### PR DESCRIPTION
**Pull request by annapowellsmith**
I'm not spending a lot of time styling and customising this, since
I assume these cards are going to get a revamp soon anyway.

screen shot 2017-05-19 at 18 04 01

### CODE REVIEW

**Comment by davidmiller** [comment]
`I assume these cards are going to get a revamp soon anyway.` -> @symroe how valid is that assumption?

**Comment by symroe** [comment]
The general idea is that each "thing" gets its own card. This might end up being really messy over time, we'll find out :)

**Comment by davidmiller** [comment]
I've heard about this TDD thing, but didn't realise it meant Thing Driven Design.

**Comment by symroe** [comment]
Thing David Does?

**Pull request merged**
