### PR TITLE
Lose the ref to 2016 on the homepage

### PR DESCRIPTION
**Pull request by JoeMitchell**
This is one suggestion...there might be other things that are better!

Or maybe just remove that line entirely...

### CODE REVIEW

**Comment by andylolz** [comment]
> Or maybe just remove that line entirely...

+1 for this.

> Who Can I Vote for
>
> Find out about the elections in your area by entering your postcode below.

^^ this is sufficient IMO.

**Comment by JoeMitchell** [comment]
Thanks Andy, will change...

**Comment by JoeMitchell** [comment]
Now hopefully good to go, though I'm not sure what it'll actually look like.

**Comment by symroe** [comment]
Thanks both!

**Pull request merged**
