### PR TITLE
Maybe using icons that exist 

### PR DESCRIPTION
**Pull request by davidmiller**
would increase your social media conversion clickthrough rate synergistic leveraging.

### CODE REVIEW

**Comment by chris48s** [comment]
Icons that exist are my favourite kind - I have a strong preference for them :D

http://fontawesome.io/icon/facebook-square/
http://fontawesome.io/icon/twitter-square/

Do you not see the icons on live? If not, this may be a more subtle issue...

screenshot at 2017-04-11 19 39 50

**Comment by chris48s** [comment]
...or that, only with a screenshot of the right site:

screenshot at 2017-04-11 19 42 54

**Comment by davidmiller** [comment]
@chris48s ooh interesting - I like subtle :) 

This is what I see on live: 

screen shot 2017-04-12 at 09 25 32

When I change the class names in the inspector to match this PR I see this:

screen shot 2017-04-12 at 09 27 48

**Comment by davidmiller** [comment]
Also interesting: 
screen shot 2017-04-12 at 09 29 43

Is that related to me rather than WCIVF ? :)

**Comment by chris48s** [comment]
I also get those 404s.
I can't reproduce the behaviour you're seeing in any OS/browser combo though. Tried it on Linux/Firefox, Linux/Chromium, Linux/Konquerer, Window/Firefox and Windows/Chrome (won't bother posting the screenshots, but I see all 3 icons every time). I thought it might be that I've already got it cached or something, but I know at least one of those browsers has never visited that site.

> ooh interesting - I like subtle :)

I, on the other hand, have a strong preference for the blindingly obvious!

**Comment by chris48s** [comment]
@davidmiller - actually, quick thought.. do you use an adblocker/other content blocker? If so, can you try disabling it on that page and reloading? Do you see the icons now?

**Pull request merged**
