### PR TITLE
Hotfix/remove mailing list form

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Ref https://app.asana.com/0/1205277833047542/1206064730900380/f

Screenshot 2023-12-13 at 10 18 07 AM copy

### CODE REVIEW

**Comment by symroe** [comment]
Hmm, something's up with the button in the footer isn't it? I reckon this should either be a link, or we update the design system to remove the background?

**Review by symroe — APPROVED** [review]
Other than the button, this is all great. Thanks for setting up the redirect too!

**Comment by VirginiaDooley** [comment]
> Hmm, something's up with the button in the footer isn't it? I reckon this should either be a link, or we update the design system to remove the background?

I just looked again at the design system and it looks like I forgot to add `class="ds-dark"` - but that assumes this should be a call to action. Should this be a button instead?

**Comment by VirginiaDooley** [comment]
> > Hmm, something's up with the button in the footer isn't it? I reckon this should either be a link, or we update the design system to remove the background?
> 
> I just looked again at the design system and it looks like I forgot to add `class="ds-dark"` - but that assumes this should be a call to action. Should this be a button instead?

@symroe Better? 

Screenshot 2023-12-13 at 10 18 07 AM copy

**Comment by symroe** [comment]
@VirginiaDooley Yes that's better. Have you pushed whatever you changed to get to that?

**Pull request closed without merging**
