### PR TITLE
Removing 'Everyone has an election on 5 May'

### PR DESCRIPTION
**Pull request by JoeMitchell**
Because it's Old News.

### CODE REVIEW

**Comment by andylolz** [comment]
Could it say 23 June instead?

**Comment by andylolz** [comment]
So that looks like this:
screen shot 2016-05-11 at 16 23 20

 * “Enter your postcode below!” can probably be removed, since it is repeated below.
 * “Find your next election!” is interesting… It hadn’t occurred to me that in the context of a referendum, “Who Can I Vote For?” is the wrong question. I suppose adding this heading makes the site relevant in a referendum context.

**Comment by JoeMitchell** [comment]
Doesn't need to be relevant to referendum really - we're not doing anything
for it. But that's the first thing we can do before we tell people about
candidates... so saying 'Find your next election' seems right to me...

Agree on the double Enter your postcode. One design suggestion was just to
get all the copy in that white box, which is probably wise.

**Comment by JoeMitchell** [comment]
@andylolz Maybe just this? 
image

**Comment by andylolz** [comment]
Hey you know… The New News here is that everyone has an election on the 23 June!

**Pull request merged**
